spring:
  application:
    name: finance-core-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8080
  forward-headers-strategy: framework
  tomcat:
    threads:
      max: 20
      min-spare: 5

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
